### PR TITLE
Add image to the home screen

### PR DESCRIPTION
**Pull request by nmentakis**

### CODE REVIEW

**Comment by lauraevans0218** [comment]
Best picture EVER!!!!!!!!!!!!!!!!

**Review by polig57 — COMMENTED** [review]
Can you add an alt name to the image

**Comment by Emilio-miloCastaneda** [comment]
looks like some good stuff.

**Comment by zachystuff** [comment]
you should size your images, and add classes. Thanks

**Comment by aevans559** [comment]
i don't like that particular section of space, can you pick a different image please

**Comment by GJoker94** [comment]
All good

**Review by zachystuff — APPROVED** [review]
Great Job!

**Review by polig57 — APPROVED** [review]
Sweet

**Review by zachystuff — APPROVED** [review]

**Pull request merged**
